version: '3.8'
services:
  frontend:
    image: your-image-name:latest
    environment:
      - API_URL=${API_URL}
      - AUTH_URL=${AUTH_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

#Cách 1
#API_URL=http://your-api-url
#AUTH_URL=http://your-auth-url

#Cách 2
# args:
#   - API_URL=http://your-api-url
#   - AUTH_URL=http://your-auth-url

#Cách 3
# docker run -d --name your-container-name -e API_URL=http://your-api-url -e AUTH_URL=http://your-auth-url your-image-name:latest

#Cách 4
# API_URL=http://your-api-url AUTH_URL=http://your-auth-url docker-compose -f docker-compose.prod.yaml up -d

# Xem tất cả biến môi trường trong container
# docker exec frontend env

# Hoặc kiểm tra cụ thể biến API_URL và AUTH_URL
# docker exec frontend printenv API_URL AUTH_URL
