version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - API_URL=${API_URL}
        - AUTH_URL=${AUTH_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
