version: '3.8'
services:
  frontend:
    build:
      context: .
      target: build
      args:
        - API_URL=${API_URL}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: nx serve ng-mf --host 0.0.0.0
    environment:
      - NODE_ENV=development
    depends_on:
      - app-remote

  app-remote:
    build:
      context: .
      target: build
      args:
        - AUTH_URL=${AUTH_URL}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4201:4201"
    command: nx serve app-remote --host 0.0.0.0

  nginx-dev:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - app-remote
